---
- name: create zookeeper Directory
  become: true
  file:
    name: /opt/zookeeper-sources
    owner: root
    group: root
    state: directory
    
- name: Download Zookeeper
  become: true
  get_url:
    dest: /opt/zookeeper-sources/{{zookeeper_tarball}}
    group: root
    owner: root
    url: "{{ zookeeper_url }}"

- name: Decompress file
  become: true
  unarchive:
    src: /opt/zookeeper-sources/{{zookeeper_tarball}}
    dest: /opt/zookeeper-sources/
    creates: /opt/zookeeper-sources/{{zookeeper_plus_version}}

- name: Symlink to /opt/zookeeper
  become: true
  file:
    src: /opt/zookeeper-sources/{{zookeeper_plus_version}}
    dest: /opt/zookeeper
    state: link
    owner: root
    group: root
